"""empty message

Revision ID: 168048b91b28
Revises: 241ab279255c
Create Date: 2020-05-18 09:39:22.975404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168048b91b28'
down_revision = '241ab279255c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.String(length=3), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'location')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
